#!/bin/bash

# Script to set up planning development environment

echo "Starting setup!"

git clone https://github.com/seakers/orekit.git
cd orekit
git fetch
git checkout xgrants

cd orekit
mvn install

echo "Setup complete!"
